### ISSUE TITLE
Issue with Node class in Python 3.11

### ISSUE THREAD

**Issue by Kiwiabacaxi** [burpeesDaily/forest-python#35] opened 2023-04-03 02:42 UTC
Hello, I'm a student who is working on a project that involves a Red-Black Tree implementation in Python. I recently tried running the code that uses the Node class provided in the repository with Python 3.11, and it gave me an error message. I'm not quite sure what the issue is, but I think it might have to do with the default value assignments for the left, right, parent attributes in the Node class.

Here is the original code that was causing issues:
```python
@dataclass
class Node:
    """Red-Black Tree non-leaf node definition."""

    key: Any
    data: Any
    left: Union["Node", Leaf] = Leaf()
    right: Union["Node", Leaf] = Leaf()
    parent: Union["Node", Leaf] = Leaf()
    color: Color = Color.RED

``` 

After some research, I found a potential solution that involves using field with default_factory=Leaf instead of assigning Leaf() directly as the default value. Here is the updated code:

```python
@dataclass
class Node:
    """Red-Black Tree non-leaf node definition."""

    key: Any
    data: Any
    left: Union["Node", Leaf] = field(default_factory=Leaf)
    right: Union["Node", Leaf] = field(default_factory=Leaf)
    parent: Union["Node", Leaf] = field(default_factory=Leaf)
    color: Color = Color.RED

``` 

I'm not entirely sure if this is the correct solution or if there might be other issues with the code, but I thought it might be worth bringing up to see if anyone else has experienced similar issues or has any suggestions for a fix.

Thank you for your time and assistance with this issue.

**Comment by burpeesDaily** [comment] 2024-02-26 07:49
@Kiwiabacaxi Thank you for bringing up this issue. The issue is that the `Leaf` class is mutable, and the `Node` class uses `Leaf` as default in `right` and  `left`. It seems Python 3.11 no longer allows that. 
The problem with that is when the default value of a member of a class is a mutable type, All instances of this class share the same instance, which could be a bug in most cases. The original idea is that the `Leaf` class is a constant, and there should be only one `Leaf` instance, so it's okay that the `Leaf` class is mutable. 
But the better way to implement it is to make the `Leaf` immutable. The easiest way to do so with a `dataclass` is to make the `frozen` `true` (See https://docs.python.org/3/library/dataclasses.html#module-contents).
Your solution may work as well, but it will affect other methods and require more code changes.
The issue has been fixed in this PR https://github.com/burpeesDaily/forest-python/pull/37; feel free to take a look.
Thank you again for pointing this out.

**Closed** 2024-02-26 07:49 UTC
